### ISSUE TITLE
[Feature] Some suggession

### ISSUE THREAD

**Issue by srdr0p** [Jasper-1024/NoWakeLock#1]
1. 唤醒锁和定时器可以反查应用, 方便确定是否可以直接禁用.
2. 长按条目支持复制锁或定时器的内容,方便编写规则.
3. 正则界面提供测试正则功能, 例如, 不确定\d或\\d哪个写法是正确的. 另外这个正则是针对指定应用的还是全局的?
谢谢作者

**Comment by Jasper-1024** [comment]
1.已经列入 beta 版计划中.
2.长按复制内容这一条,放在beta版结束时候吧,可能与现在的代码有点冲突.
3.正则是应用级别的,全局正则范围太广,如果有误杀后果太严重.测试正则,这个可以加,但是优先级会比较低,可能需要重写正则部分..

**Comment by srdr0p** [comment]
谢谢，期待Beta版。

**Comment by Jasper-1024** [comment]
> 
> 
> 谢谢，期待Beta版。

具体应用开发计划&&进度详情见 https://jasper-1024.github.io/jasper/7qweijglc7/

**Comment by srdr0p** [comment]
发现微信有个问题，系统是MIUI 12，使用正则禁用所有ALARM_ACTION后, 微信内置WebView加载很慢, 从logcat得到的错误信息是微信申请了超过500个定时器,导致PUSH进程被杀，希望有办法规避这个问题。具体logcat消息等下次复现后贴出来。

**Comment by Jasper-1024** [comment]
> 
> 
> 发现微信有个问题，系统是MIUI 12，使用正则禁用所有ALARM_ACTION后, 微信内置WebView加载很慢, 从logcat得到的错误信息是微信申请了超过500个定时器,导致PUSH进程被杀，希望有办法规避这个问题。具体logcat消息等下次复现后贴出来。

请到时重开一个issue.
因为精力和能力限制,现在一些 beta 阶段的计划都在延期,尽力但不能保证.
