### ISSUE TITLE
NoWakelock vs DeepSleep: Differences?

### ISSUE THREAD

**Issue by rdtm443** [Jasper-1024/NoWakeLock#12]
Hey there

While searching for a solution to lower my idle drain (although not too bad, currently at 1.1%, on MIUIMix), I stumbled over your two modules, that address this kind of problem. 

Now, what is the difference between these two? Which is currently maintained etc.?

Thanks a lot !

**Comment by Jasper-1024** [comment]
Sorry for the delay.recently my life has changed dramatically, don't worry, for the better. But I've had to spend all my time dealing with it.

DeepSleep is easier to use, so if it meets your needs, use it.
Nowakelcok gives the user finer control over wakelcok/alarm/service, which is more complex to use.

DeepSleep / Nowakelcok are both under continuous maintenance, and when DeepSleep is stable, there will not be many updates. The opposite is true for Nowakelcok, which has not yet reached a stable version.
