### ISSUE TITLE
miui14 安卓13，服务显示不全

### ISSUE THREAD

**Issue by PHCSJC** [Jasper-1024/NoWakeLock#15]
版本beta5，lsposed下，模块已激活，但哔哩哔哩的服务显示不全，下面第一个图是爱玩机里显示的，其中第1个服务在NoWakeLock里看不到，第2个服务是可以看到的，我的需求是要禁用第1个服务

![Screenshot_2023-02-01-10-12-53-385_com byyoung se](https://user-images.githubusercontent.com/22064544/215928775-acad946f-53be-45f2-b7b4-707e9592770c.jpg)
![Screenshot_2023-02-01-10-13-42-780_com js nowakel](https://user-images.githubusercontent.com/22064544/215928811-06f59c5b-0686-4d41-a3f7-6798325bf35b.jpg)

**Comment by Jasper-1024** [comment]
这是服务启动流程造成,目前 nowakelock 这一块只获取了通过 com.android.server.am.ActiveServices 启动的服务,这样肯定有遗漏.

寻求禁用服务建议使用 -> [app manger](https://github.com/MuntashirAkon/AppManager)
