### ISSUE TITLE
Any plans for stability release and description 

### ISSUE THREAD

**Issue by varunpilankar** [Jasper-1024/NoWakeLock#3]
It would be great to see a stable build and some kind of description of each wakelocks and alarms.. At least the general ones

**Comment by Jasper-1024** [comment]
Sorry, it's been a difficult time for me, too much work to be done and almost no personal time.

The earliest this can end is early 2022, so I can't commit to anything until then.

**Comment by varunpilankar** [comment]
Noted.. Looking forward to the next update!

**Comment by varunpilankar** [comment]
Whenever I make changes to wakelock or alarms and try to reset to default due to some malfunction.. It doesn't get restored.. Major problem

**Comment by chaoscreater** [comment]
Is there a quick guide on how to use this?

I installed Riru and LSPosed. LSPosed shows it's activated and I can see NoWakeLock in the module section and enabled. But I don't see any alarms, services or wakelocks to disable in NoWakeLock...

**Comment by varunpilankar** [comment]
> Is there a quick guide on how to use this?
> 
> I installed Riru and LSPosed. LSPosed shows it's activated and I can see NoWakeLock in the module section and enabled. But I don't see any alarms, services or wakelocks to disable in NoWakeLock...

 Remove NoWakeLock from battery optimized list? Don't optimize it.

**Comment by chaoscreater** [comment]
> 
> 
> > Is there a quick guide on how to use this?
> > I installed Riru and LSPosed. LSPosed shows it's activated and I can see NoWakeLock in the module section and enabled. But I don't see any alarms, services or wakelocks to disable in NoWakeLock...
> 
> Remove NoWakeLock from battery optimized list? Don't optimize it.

Done that already.

**Comment by varunpilankar** [comment]
Which Android version are you running?

App works only in battery discharging state. I have tested it on Android 10 - works okish but a bit buggy. Worth a try though.

**Comment by chaoscreater** [comment]
running Android 11, specifically MIUI 12.5.5 Android 11.

**Comment by varunpilankar** [comment]
I didn't test it on A11.. I doubt if it supports 11.. Maybe @Jasper-1024 is the right person to answer this

**Comment by chaoscreater** [comment]
> 
> 
> I didn't test it on A11.. I doubt if it supports 11.. Maybe @Jasper-1024 is the right person to answer this

Well, it says it works for A11 and that's why I downloaded it. It's supposed to be a replacement for Amplify (which doesn't work on newer Android versions).

Are you using Edxposed or LSposed? I'm trying Edxposed now to see if that makes a difference...

**Comment by chaoscreater** [comment]
OK, confirmed that this does not work with LSPosed but works with EDXposed. LSPosed is actually better and more preferred compared to EDXposed and this seems to be the common consensus that I found online.

Anyway, to install EDXposed, you have to use Riru v25 and not the latest one. This is mentioned in their Github. Once I got EDXposed working, NoWakeLock can now list alarms and wakelocks, etc.

**Comment by Jasper-1024** [comment]
Nowakelock work with LSPosed on aosp, LSPosed  need select System Framework.

**Comment by Jasper-1024** [comment]
@chaoscreater @varunpilankar  Nowakelock work with LSPosed on aosp android R, LSPosed need select System Framework.
I'm not sure if nowakelock will work properly on miui. For the following reasons. 
Records for wake-up locks etc. need to be written to nowakelock via the content provider, which wakes up nowakelock, a process that is managed by the system and does not cause additional power consumption. But miui is usually very restrictive with content providers.

**Comment by Jasper-1024** [comment]
@chaoscreater @varunpilankar 
I apologize for the incomplete documentation, I had very little personal time. It was a difficult time for me. 
But I'm not giving up on this project, and I'll work on these issues as soon as my life can be stabilized.

**Comment by chaoscreater** [comment]
@Jasper-1024 

Thanks for your reply. Good to know that it works with LSPosed. I didn't have System Framework selected, so maybe that's why it didn't work for me.

I'm currently using EDXposed with Riru v25 on MIUI 12.5.5 Android 11 (stock ROM). Your app is working fine so far. I can see wakelocks, alarms and services and it seems to be doing a good job at blocking the wakelocks. I can see in GSAM Battery Monitor that Google Play Service wakelocks are not showing a high number now. So I'm happy that it's working so far.

Thanks for making this project. I've tried to find alternatives to Amplify (in Magisk repo and Xposed repo) and there aren't many solutions. Yours is currently working the best for me.

**Comment by Jasper-1024** [comment]
issue closed

**Comment by Jasper-1024** [comment]
issue closed
