### ISSUE TITLE
Not working on LSPosed

### ISSUE THREAD

**Issue by user828919** [Jasper-1024/NoWakeLock#4]
Hi Jasper,

Since Magisk v24, Zygisk is used for root hiding. But Riru would not work when zygisk is enabled.
I used LSPosed to replace Edxposed. But NoWakeLock is not woking. (I have checked all apps in LSPosed for NoWakeLock)

My phone is OnePlus 7 Pro with Android 11.

**Comment by Jasper-1024** [comment]
LSPosed need select System Framework, no need select apps.

**Comment by user828919** [comment]
Sorry, I forgot to restart after activate the module. Thank you.
