### ISSUE TITLE
在miui13上出错。无法显示wakelock、alarm和sync

### ISSUE THREAD

**Issue by simplerick-simplefun** [Jasper-1024/NoWakeLock#5]
在miui13上出错。无法显示wakelock、alarm和sync。
使用场景：
LSposed 1.8.3 - Zygisk
Magisk 25.1
MIUI 13.0.21 稳定版
Android 12
Redmi K50

**Comment by Jasper-1024** [comment]
尝试 play 的 2.0.0 -alpha 版本

**Comment by Jasper-1024** [comment]
似乎 2.0.0 -alpha 版本推出各个地方有差别,还没有铺开.

**Comment by simplerick-simplefun** [comment]
应用界面点开每个应用，看到的唤醒锁、服务、定时器都是空的。
但是点开右边的全部唤醒锁、服务、定时器，就能看到列表里面有内容，每一个具体的条目也有计数。
仔细看一下，很多条目都归到了 android系统 应用下面。但是似乎有一些用户应用的唤醒锁服务和定时器完全没有显示。

2.0.0 -alpha 版本
![Screenshot_2022-07-09-10-25-50-798_com js nowakelock](https://user-images.githubusercontent.com/13503950/178088164-f9eb818c-157f-47b9-be4e-736c4ea8d8db.jpg)
![Screenshot_2022-07-09-10-25-43-793_com js nowakelock](https://user-images.githubusercontent.com/13503950/178088167-d64f3a94-a674-41b1-b464-f1238807585c.jpg)

![Screenshot_2022-07-09-10-31-30-634_com js nowakelock](https://user-images.githubusercontent.com/13503950/178088460-fda8da37-8841-4abb-8ca9-bc46ba7ea399.jpg)
![Screenshot_2022-07-09-10-42-17-076_com js nowakelock](https://user-images.githubusercontent.com/13503950/178088705-0d140b66-79f9-4029-8c62-02f5b4a685a2.jpg)
![Screenshot_2022-07-09-10-42-08-089_com js nowakelock](https://user-images.githubusercontent.com/13503950/178088721-9a362bf5-aac9-4a69-8ffd-acf8d0ef9e5d.jpg)

**Comment by Jasper-1024** [comment]
这样已经是正常工作了,android 系统下这样是正常的,因为 系统框架签名的 进程 申请的  wakelock or alarm 都会算到,android 系统下.

用户应用没有更多显示
1. 应用本身没有申请 wakelock or alarm.
2. 或者 本来有数据因为插电/拔电 数据被清除了,尝试在设置内暂时关掉数据清理. 然后打开微信 放后台,等一段时间 刷新下看看.

**Comment by simplerick-simplefun** [comment]
嗯。确实如此。可以close了。感谢更新及回复！
