### ISSUE TITLE
An input bug

### ISSUE THREAD

**Issue by Jasper-1024** [Jasper-1024/NoWakeLock#9]
the first input 6900, it will change to 0069.

**Comment by chaoscreater** [comment]
If you put e.g. 900, it'll become 009 instead as well.

**Comment by Jasper-1024** [comment]
> If you put e.g. 900, it'll become 009 instead as well.

Yes, i am just very busy, this bug will be fix on next version, i think it will come before 22.10.7.

**Comment by Jasper-1024** [comment]
I think this bug is fixed on 2.0.0-beta3.
